# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dustin/Repos/EntSnapRay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dustin/Repos/EntSnapRay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dustin/Repos/EntSnapRay/CMakeFiles /home/dustin/Repos/EntSnapRay//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dustin/Repos/EntSnapRay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EntSnap

# Build rule for target.
EntSnap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EntSnap
.PHONY : EntSnap

# fast build rule for target.
EntSnap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/build
.PHONY : EntSnap/fast

src/App.o: src/App.cpp.o

.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i

.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s

.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/Component.o: src/Component.cpp.o

.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i

.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s

.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/CustomGuis.o: src/CustomGuis.cpp.o

.PHONY : src/CustomGuis.o

# target to build an object file
src/CustomGuis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/CustomGuis.cpp.o
.PHONY : src/CustomGuis.cpp.o

src/CustomGuis.i: src/CustomGuis.cpp.i

.PHONY : src/CustomGuis.i

# target to preprocess a source file
src/CustomGuis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/CustomGuis.cpp.i
.PHONY : src/CustomGuis.cpp.i

src/CustomGuis.s: src/CustomGuis.cpp.s

.PHONY : src/CustomGuis.s

# target to generate assembly for a file
src/CustomGuis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/CustomGuis.cpp.s
.PHONY : src/CustomGuis.cpp.s

src/Entity.o: src/Entity.cpp.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/GuiFileDialog.o: src/GuiFileDialog.cpp.o

.PHONY : src/GuiFileDialog.o

# target to build an object file
src/GuiFileDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/GuiFileDialog.cpp.o
.PHONY : src/GuiFileDialog.cpp.o

src/GuiFileDialog.i: src/GuiFileDialog.cpp.i

.PHONY : src/GuiFileDialog.i

# target to preprocess a source file
src/GuiFileDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/GuiFileDialog.cpp.i
.PHONY : src/GuiFileDialog.cpp.i

src/GuiFileDialog.s: src/GuiFileDialog.cpp.s

.PHONY : src/GuiFileDialog.s

# target to generate assembly for a file
src/GuiFileDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/GuiFileDialog.cpp.s
.PHONY : src/GuiFileDialog.cpp.s

src/Project.o: src/Project.cpp.o

.PHONY : src/Project.o

# target to build an object file
src/Project.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Project.cpp.o
.PHONY : src/Project.cpp.o

src/Project.i: src/Project.cpp.i

.PHONY : src/Project.i

# target to preprocess a source file
src/Project.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Project.cpp.i
.PHONY : src/Project.cpp.i

src/Project.s: src/Project.cpp.s

.PHONY : src/Project.s

# target to generate assembly for a file
src/Project.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/Project.cpp.s
.PHONY : src/Project.cpp.s

src/SidePanel.o: src/SidePanel.cpp.o

.PHONY : src/SidePanel.o

# target to build an object file
src/SidePanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/SidePanel.cpp.o
.PHONY : src/SidePanel.cpp.o

src/SidePanel.i: src/SidePanel.cpp.i

.PHONY : src/SidePanel.i

# target to preprocess a source file
src/SidePanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/SidePanel.cpp.i
.PHONY : src/SidePanel.cpp.i

src/SidePanel.s: src/SidePanel.cpp.s

.PHONY : src/SidePanel.s

# target to generate assembly for a file
src/SidePanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/SidePanel.cpp.s
.PHONY : src/SidePanel.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EntSnap.dir/build.make CMakeFiles/EntSnap.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EntSnap"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/CustomGuis.o"
	@echo "... src/CustomGuis.i"
	@echo "... src/CustomGuis.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/GuiFileDialog.o"
	@echo "... src/GuiFileDialog.i"
	@echo "... src/GuiFileDialog.s"
	@echo "... src/Project.o"
	@echo "... src/Project.i"
	@echo "... src/Project.s"
	@echo "... src/SidePanel.o"
	@echo "... src/SidePanel.i"
	@echo "... src/SidePanel.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

